package:
  name: "pytessel"
  version: "0.1.2"

source:
  path: .

requirements:
  build:
    - numpy
    - tqdm

  host:
    - pip
    - python
    - setuptools
    - cython
    - numpy

  run:
    - python
    - numpy

test:
  requires:
    - numpy
    - setuptools
    - nose
  source_files:
    - tests/*.py
  commands:
    - nosetests tests

about:
  home: https://github.com/ifilot/pytessel
  license: GPL3
  license_family: GPL
  summary: Python package for building isosurfaces from 3D scalar fields
  description: See the package README.md for more information.
